#!/usr/bin/env python3
"""Probe schema-based binary `.json` payloads.

Some Endfield files live under logical `.json` paths but are binary payloads
after VFS decryption. This script is a lightweight research helper: it prints
header bytes, likely length-prefixed UTF-8 strings, and optional matches against
a decoded JSON reference from AKEDB.
"""

from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable
from urllib.request import urlopen

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from vfs_crypto import decrypt_vfs_file


DEFAULT_DB = PROJECT_ROOT / "data" / "endfield-vfs-index.sqlite"
DEFAULT_MAX_OFFSET = 8192
DEFAULT_MAX_STRINGS = 80


@dataclass(frozen=True)
class StringProbe:
    offset: int
    length: int
    text: str


def parse_args(argv: Iterable[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--id", type=int, help="file id in the VFS index database")
    source.add_argument("--binary", type=Path, help="already decrypted binary payload")
    parser.add_argument("--db", type=Path, default=DEFAULT_DB, help="SQLite database generated by server.py")
    parser.add_argument("--reference-json", type=Path, help="decoded JSON reference file")
    parser.add_argument("--reference-url", help="decoded JSON reference URL")
    parser.add_argument("--max-offset", type=int, default=DEFAULT_MAX_OFFSET, help="bytes to scan for string probes")
    parser.add_argument("--max-strings", type=int, default=DEFAULT_MAX_STRINGS, help="max string probes to show")
    parser.add_argument("--output", type=Path, help="write Markdown report to this file")
    return parser.parse_args(list(argv))


def read_vfs_payload(db_path: Path, file_id: int) -> tuple[bytes, str]:
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    try:
        row = conn.execute("SELECT * FROM files WHERE id = ?", (file_id,)).fetchone()
        if row is None:
            raise SystemExit(f"file id not found: {file_id}")
        chunk_path = Path(row["chunk_path"])
        with chunk_path.open("rb") as file:
            file.seek(int(row["offset"]))
            data = file.read(int(row["length"]))
        if row["encrypted"]:
            data = decrypt_vfs_file(data, int(row["iv_seed"]))
        return data, f"id {file_id}: {row['source_logical_id']}"
    finally:
        conn.close()


def read_reference(args: argparse.Namespace) -> Any | None:
    if args.reference_json:
        return json.loads(args.reference_json.read_text(encoding="utf-8-sig"))
    if args.reference_url:
        with urlopen(args.reference_url, timeout=30) as response:
            return json.loads(response.read().decode("utf-8-sig"))
    return None


def length_prefixed_utf8_strings(data: bytes, max_offset: int, max_count: int) -> list[StringProbe]:
    probes: list[StringProbe] = []
    scan_end = min(max(len(data) - 4, 0), max_offset)
    for offset in range(scan_end):
        length = int.from_bytes(data[offset : offset + 4], "little")
        if length < 4 or length > 240 or offset + 4 + length > len(data):
            continue
        raw = data[offset + 4 : offset + 4 + length]
        try:
            text = raw.decode("utf-8")
        except UnicodeDecodeError:
            continue
        if not text or any(ord(char) < 32 and char not in "\t\r\n" for char in text):
            continue
        probes.append(StringProbe(offset=offset, length=length, text=text))
        if len(probes) >= max_count:
            break
    return probes


def walk_strings(value: Any, path: str = "$") -> Iterable[tuple[str, str]]:
    if isinstance(value, str):
        yield path, value
    elif isinstance(value, list):
        for index, item in enumerate(value):
            yield from walk_strings(item, f"{path}[{index}]")
    elif isinstance(value, dict):
        for key, item in value.items():
            escaped_key = str(key).replace("'", "\\'")
            yield from walk_strings(item, f"{path}['{escaped_key}']")


def reference_matches(reference: Any, probes: list[StringProbe]) -> dict[str, list[str]]:
    if reference is None:
        return {}
    reference_strings = list(walk_strings(reference))
    matches: dict[str, list[str]] = {}
    for probe in probes:
        paths = [path for path, text in reference_strings if text == probe.text]
        if not paths:
            paths = [path for path, text in reference_strings if probe.text in text or text in probe.text]
        if paths:
            matches[probe.text] = paths[:8]
    return matches


def hex_lines(data: bytes, max_bytes: int = 192) -> str:
    rows = []
    sample = data[:max_bytes]
    for offset in range(0, len(sample), 16):
        row = sample[offset : offset + 16]
        hex_part = " ".join(f"{byte:02x}" for byte in row)
        ascii_part = "".join(chr(byte) if 32 <= byte < 127 else "." for byte in row)
        rows.append(f"{offset:04x}: {hex_part:<47} {ascii_part}")
    return "\n".join(rows)


def top_level_summary(reference: Any) -> str:
    if not isinstance(reference, dict):
        return "_No object reference loaded._"
    rows = []
    for key, value in reference.items():
        if isinstance(value, dict):
            kind = f"object({len(value)})"
        elif isinstance(value, list):
            kind = f"array({len(value)})"
        else:
            kind = type(value).__name__
        rows.append(f"| `{key}` | {kind} | `{str(value)[:80]}` |")
    return "\n".join(["| Field | Type | Preview |", "| --- | --- | --- |", *rows])


def build_report(label: str, data: bytes, probes: list[StringProbe], reference: Any | None) -> str:
    first_byte = data[0] if data else None
    matches = reference_matches(reference, probes)
    probe_rows = []
    for probe in probes:
        paths = matches.get(probe.text, [])
        match_text = "<br>".join(f"`{path}`" for path in paths) if paths else ""
        probe_rows.append(f"| `0x{probe.offset:x}` | {probe.length} | `{probe.text}` | {match_text} |")
    if not probe_rows:
        probe_rows.append("| _none_ |  |  |  |")

    return "\n".join(
        [
            f"# Binary JSON Probe: {label}",
            "",
            "## Payload",
            "",
            f"- Bytes: `{len(data)}`",
            f"- First byte: `{first_byte if first_byte is not None else 'N/A'}`",
            f"- First byte hex: `{f'0x{first_byte:02x}' if first_byte is not None else 'N/A'}`",
            "- First byte may be an object member count for this family, but this is not a full decoder.",
            "",
            "```text",
            hex_lines(data),
            "```",
            "",
            "## Length-Prefixed UTF-8 Candidates",
            "",
            "| Offset | Length | Text | Reference JSON matches |",
            "| --- | ---: | --- | --- |",
            *probe_rows,
            "",
            "## Reference JSON Top-Level Fields",
            "",
            top_level_summary(reference),
            "",
            "## Notes",
            "",
            "- These files are already VFS-decrypted before probing.",
            "- The payload appears to be schema-based binary data, not self-describing JSON.",
            "- Full decoding needs the field order/schema or a reliable generated formatter.",
        ]
    )


def main(argv: Iterable[str]) -> int:
    args = parse_args(argv)
    if args.binary:
        data = args.binary.read_bytes()
        label = str(args.binary)
    else:
        data, label = read_vfs_payload(args.db, args.id)
    reference = read_reference(args)
    probes = length_prefixed_utf8_strings(data, args.max_offset, args.max_strings)
    report = build_report(label, data, probes, reference)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(report, encoding="utf-8")
    else:
        print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
