#!/usr/bin/env python3
"""Scan decrypted JsonData files and classify their real payload format.

The VFS logical path can contain files ending in `.json` whose decrypted payload
is not UTF-8 JSON text. This diagnostic script reads records from the local VFS
SQLite database, decrypts each selected file slice, and writes a Markdown report
that separates real JSON text from binary payloads and other edge cases.
"""

from __future__ import annotations

import argparse
import json
import sqlite3
import sys
import time
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from server import decode_text, decrypt_vfs_file, looks_like_text


DEFAULT_DB = PROJECT_ROOT / "data" / "endfield-vfs-index.sqlite"
DEFAULT_OUTPUT = PROJECT_ROOT / "data" / "reports" / "jsondata-format-report.md"
DEFAULT_PREFIX = "JsonData/Data/Json"


@dataclass
class ScanResult:
    path: str
    file_id: int
    source: str
    chunk_path: str
    offset: int
    length: int
    encrypted: bool
    category: str
    detail: str = ""
    first16: str = ""
    signature8: str = ""
    strings: tuple[str, ...] = ()


def parse_args(argv: Iterable[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", type=Path, default=DEFAULT_DB, help="SQLite database generated by server.py")
    parser.add_argument("--scope", default="effective", help="entries.scope to scan, usually effective")
    parser.add_argument("--prefix", default=DEFAULT_PREFIX, help="logical directory prefix to scan")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Markdown report output path")
    parser.add_argument("--limit", type=int, default=0, help="limit scanned records for quick tests")
    parser.add_argument("--sample-limit", type=int, default=30, help="max samples per report section")
    parser.add_argument("--progress-every", type=int, default=1000, help="print progress every N files, 0 disables")
    return parser.parse_args(list(argv))


def normalize_prefix(prefix: str) -> str:
    return prefix.replace("\\", "/").strip("/")


def read_record_data(row: sqlite3.Row) -> bytes:
    chunk_path = Path(row["chunk_path"])
    with chunk_path.open("rb") as file:
        file.seek(int(row["offset"]))
        data = file.read(int(row["length"]))
    if row["encrypted"]:
        return decrypt_vfs_file(data, int(row["iv_seed"]))
    return data


def extract_ascii_strings(data: bytes, *, min_len: int = 5, limit: int = 6) -> tuple[str, ...]:
    strings: list[str] = []
    current = bytearray()
    for byte in data:
        if 32 <= byte <= 126:
            current.append(byte)
            continue
        if len(current) >= min_len:
            strings.append(current.decode("ascii", errors="replace"))
            if len(strings) >= limit:
                break
        current.clear()
    if len(strings) < limit and len(current) >= min_len:
        strings.append(current.decode("ascii", errors="replace"))
    return tuple(strings[:limit])


def classify_text_payload(data: bytes) -> tuple[str, str]:
    text, encoding = decode_text(data)
    if text is None or not looks_like_text(text):
        return "binary", "decoded payload is not readable text"
    try:
        json.loads(text)
    except json.JSONDecodeError as error:
        return "text-not-json", f"{encoding or 'text'}; JSON parse failed at {error.pos}: {error.msg}"
    return "json-text", encoding or "text"


def category_label(category: str) -> str:
    return {
        "json-text": "JSON 文本",
        "text-not-json": "可读文本但不是 JSON",
        "binary": "已解密二进制",
        "missing-chunk": "缺少 chunk",
        "read-error": "读取错误",
    }.get(category, category)


def top_dir(path: str, prefix: str) -> str:
    normalized = path.replace("\\", "/").strip("/")
    if normalized.startswith(prefix + "/"):
        rest = normalized[len(prefix) + 1 :]
    else:
        rest = normalized
    return rest.split("/", 1)[0] if rest else "."


def second_dir(path: str, prefix: str) -> str:
    normalized = path.replace("\\", "/").strip("/")
    if normalized.startswith(prefix + "/"):
        rest = normalized[len(prefix) + 1 :]
    else:
        rest = normalized
    parts = rest.split("/")
    if len(parts) >= 2:
        return "/".join(parts[:2])
    return parts[0] if parts and parts[0] else "."


def query_records(conn: sqlite3.Connection, scope: str, prefix: str, limit: int) -> list[sqlite3.Row]:
    pattern = f"{prefix}/%.json"
    sql = """
        SELECT e.path, f.*
        FROM entries e
        JOIN files f ON f.id = e.file_id
        WHERE e.scope = ? AND e.type = 'file' AND e.path LIKE ?
        ORDER BY e.path COLLATE NOCASE
    """
    if limit > 0:
        sql += " LIMIT ?"
        return list(conn.execute(sql, (scope, pattern, limit)))
    return list(conn.execute(sql, (scope, pattern)))


def scan(args: argparse.Namespace) -> list[ScanResult]:
    if not args.db.exists():
        raise SystemExit(f"database not found: {args.db}")
    prefix = normalize_prefix(args.prefix)
    conn = sqlite3.connect(args.db)
    conn.row_factory = sqlite3.Row
    rows = query_records(conn, args.scope, prefix, args.limit)
    started = time.time()
    results: list[ScanResult] = []
    for index, row in enumerate(rows, 1):
        chunk_path = Path(row["chunk_path"])
        base = {
            "path": row["path"],
            "file_id": int(row["id"]),
            "source": row["source"],
            "chunk_path": row["chunk_path"],
            "offset": int(row["offset"]),
            "length": int(row["length"]),
            "encrypted": bool(row["encrypted"]),
        }
        if not chunk_path.exists():
            results.append(ScanResult(**base, category="missing-chunk", detail="chunk path does not exist"))
            continue
        try:
            data = read_record_data(row)
            category, detail = classify_text_payload(data)
            first16 = data[:16].hex(" ")
            signature8 = data[:8].hex(" ")
            strings = extract_ascii_strings(data[:8192]) if category == "binary" else ()
            results.append(
                ScanResult(
                    **base,
                    category=category,
                    detail=detail,
                    first16=first16,
                    signature8=signature8,
                    strings=strings,
                )
            )
        except Exception as error:  # noqa: BLE001 - diagnostics should continue across bad records.
            results.append(ScanResult(**base, category="read-error", detail=f"{type(error).__name__}: {error}"))

        if args.progress_every and index % args.progress_every == 0:
            elapsed = time.time() - started
            print(f"scanned {index:,}/{len(rows):,} files in {elapsed:.1f}s", flush=True)
    return results


def markdown_table(headers: list[str], rows: list[list[str]]) -> str:
    if not rows:
        return "_无_\n"
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(cell.replace("\n", "<br>") for cell in row) + " |")
    return "\n".join(lines) + "\n"


def summarize_by_directory(results: list[ScanResult], prefix: str) -> str:
    per_dir: dict[str, Counter[str]] = defaultdict(Counter)
    for result in results:
        per_dir[top_dir(result.path, prefix)][result.category] += 1
    rows: list[list[str]] = []
    for directory, counts in sorted(per_dir.items()):
        total = sum(counts.values())
        rows.append(
            [
                f"`{directory}`",
                str(total),
                str(counts.get("json-text", 0)),
                str(counts.get("binary", 0)),
                str(counts.get("text-not-json", 0)),
                str(counts.get("missing-chunk", 0)),
                str(counts.get("read-error", 0)),
            ]
        )
    return markdown_table(["目录", "总数", "JSON", "二进制", "非 JSON 文本", "缺 chunk", "错误"], rows)


def summarize_binary_signatures(results: list[ScanResult], sample_limit: int) -> str:
    counter = Counter(result.signature8 for result in results if result.category == "binary")
    rows: list[list[str]] = []
    for signature, count in counter.most_common(sample_limit):
        sample = next(result for result in results if result.signature8 == signature)
        rows.append([f"`{signature}`", str(count), f"`{sample.path}`", "; ".join(sample.strings[:3])])
    return markdown_table(["前 8 字节", "数量", "样例", "可见字符串"], rows)


def sample_rows(results: list[ScanResult], category: str, prefix: str, sample_limit: int) -> list[list[str]]:
    rows: list[list[str]] = []
    for result in [item for item in results if item.category == category][:sample_limit]:
        rows.append(
            [
                f"`{result.file_id}`",
                f"`{second_dir(result.path, prefix)}`",
                f"`{result.path}`",
                result.source,
                str(result.length),
                f"`{result.first16}`" if result.first16 else "",
                "; ".join(result.strings) if result.strings else result.detail,
            ]
        )
    return rows


def write_report(args: argparse.Namespace, results: list[ScanResult]) -> None:
    prefix = normalize_prefix(args.prefix)
    counts = Counter(result.category for result in results)
    total = len(results)
    lines = [
        "# JsonData 文件格式诊断报告",
        "",
        f"- 数据库：`{args.db}`",
        f"- scope：`{args.scope}`",
        f"- 扫描前缀：`{prefix}`",
        f"- 扫描文件数：{total}",
        f"- 生成时间：{time.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "## 总览",
        "",
        markdown_table(
            ["分类", "数量", "占比"],
            [
                [
                    category_label(category),
                    str(count),
                    f"{(count / total * 100):.2f}%" if total else "0.00%",
                ]
                for category, count in counts.most_common()
            ],
        ),
        "## 按一级目录统计",
        "",
        summarize_by_directory(results, prefix),
        "## 二进制签名样例",
        "",
        summarize_binary_signatures(results, args.sample_limit),
        "## 二进制文件样例",
        "",
        markdown_table(
            ["id", "目录", "路径", "来源", "长度", "前 16 字节", "可见字符串/说明"],
            sample_rows(results, "binary", prefix, args.sample_limit),
        ),
        "## 可读文本但不是 JSON 的样例",
        "",
        markdown_table(
            ["id", "目录", "路径", "来源", "长度", "前 16 字节", "说明"],
            sample_rows(results, "text-not-json", prefix, args.sample_limit),
        ),
        "## 缺失或读取错误样例",
        "",
        markdown_table(
            ["id", "目录", "路径", "来源", "长度", "前 16 字节", "说明"],
            sample_rows(results, "missing-chunk", prefix, args.sample_limit)
            + sample_rows(results, "read-error", prefix, args.sample_limit),
        ),
    ]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    results = scan(args)
    write_report(args, results)
    counts = Counter(result.category for result in results)
    print(f"wrote report: {args.output}")
    print(", ".join(f"{category}={count}" for category, count in counts.most_common()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
